apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-group-5
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: git@github.com:the-cloud-camp/tcc-k8s-config-nonprd.git
    targetRevision: group-5
    path: manifest
  destination:
    name: in-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true