apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kai-nuxtjs-application
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: git@github.com:the-cloud-camp/tcc-k8s-config-nonprd.git
    targetRevision: main
    path: kai-nuxtjs
  destination:
    name: in-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true