apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-group-5
  namespace: argocd
  labels:
    group: group-5
spec:
  project: default
  source: 
    repoURL: git@github.com:the-cloud-camp/tcc-group-5.git
    targetRevision: develop
    path: argocd/dev
  destination:
    name: in-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true