apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-group-4-prod
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: git@github.com:the-cloud-camp/tcc-k8s-config.git
    targetRevision: group-4
    path: app
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
