apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-application-rg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source: 
    repoURL: git@github.com:the-cloud-camp/tcc-k8s-app.git
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true