apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-application-rg
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: git@github.com:the-cloud-camp/tcc-k8s-app.git
    targetRevision: main
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true